version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file lambdas/process_schools_queue/template.yaml --s3-bucket schools-lambdas --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
