version: 0.1
phases:
  build:
    commands:
      - echo installing npm packages
      - cd $CODEBUILD_SRC_DIR/get-schools-toronto
      - npm install
  install:
    commands:
      - aws cloudformation package --template-file lambdas/get_schools_toronto/template.yaml --s3-bucket schools-lambdas --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
