
version: 0.1
phases:
  install:
    commands:
      - echo start install phases
      - npm --prefix $CODEBUILD_SRC_DIR/lambdas/git_webhook/webhook install
      - aws cloudformation package --template-file lambdas/git_webhook/template.yaml --s3-bucket schools-lambdas --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
