
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Git Webhook for CD
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  WebHookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Role: "arn:aws:iam::241056173073:role/LambdaRoleChattes1"
      Events:
        WebHook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /web-hook
            Method: post
      Environment:
        Variables:
          REGION: us-east-2
